In [1]:
import numpy as np

In [5]:
from scipy import io as spio
a = np.ones((3,3))
spio.savemat('file.mat',{'a':a})
data = spio.loadmat('file.mat',struct_as_record=True)
'''
    # likely:
    from scipy import misc
    misc.imread('fname.png')
    import matplotlib.pyplot as plt
    plt.imread('fname.png')
'''
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
from scipy import linalg
arr = np.array([[1,2],[3,4]])
linalg.det(arr)
# error: linalg.det(np.ones((3,4)))

-2.0

In [11]:
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
np.allclose(np.dot(arr,iarr),np.eye(2))

True

In [14]:
arr1 = np.array([[3,2],[6,4]])
linalg.inv(arr1)

LinAlgError: singular matrix

In [15]:
arr2 = np.arange(9).reshape((3,3)) + np.diag([1,0,1])
uarr, spec, vharr = linalg.svd(arr2)
spec

array([14.88982544,  0.45294236,  0.29654967])

In [16]:
# 快速傅里叶变换
time_step = .02
period = 5
time_vec = np.arange(0,20,time_step)
sig = np.sin(2*np.pi/period*time_vec) + 0.5 * np.random.randn(time_vec.size)

In [17]:
from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size,d=time_step)
sig_fft = fftpack.fft(sig)

In [ ]:
pidxs = np.where(sample_freq > 0)
freqs = sample_freq[pidxs]
power